listen:
  port: 4040
  address: "0.0.0.0"
  metrics_endpoint: "/metrics"

namespaces:
  - name: klx_core
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" rt=$request_time uct=\"$upstream_connect_time\" uht=\"$upstream_header_time\" urt=\"$upstream_response_time\""
    source:
      files:
        - access.log
      exclude_patterns:
        - docx
        - exam_v2
    # metrics_override:
    #   prefix: "myprefix"
    # namespace_label: "vhost"
    labels:
      app: "klx_core"
      environment: "staging"
      foo: "bar"
    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
